### ISSUE TITLE
[Silvania] Lottery Payout Plans

### ISSUE THREAD

**Issue by MyNameIsKodos** [MyNameIsKodos/All-My-Random-Shit#1]
| Numbers Matched | Prize |
| --- | --- |
| 5 + Powerball | Jackpot |
| 5 | $1,000,000 |
| 4 + Powerball | $50,000 |
| 4 | $100 |
| 3 + Powerball | $100 |
| 3 | $7 |
| 2 + Powerball | $7 |
| 1 + Powerball | $4 |
| Powerball only | $2 |

Okay, so, I'm going to start a lottery for the server as a cheaper alternative to Raffles, but without the guarantee of winning. I'm going to be doing a payout system similar to America's "Powerball" payouts.  Above this paragraph is a diagram of actual payouts from Powerball. Below is a diagram of a rough version of what I want to do for payouts, and the purpose of this issue is to get everyone's feedback and suggestions.

Note that the **max** amount paid out is 75% to offset costs of running the lottery, since this is being done out of my own pocket.

EDIT: I've left out a few details.  The other 25% is NOT for profit. It's to cover the cost of ink and paper to be able to print the tickets.

Also, when there are no winners, or if a substantial amount of the total pot hasn't been won (ie someone only wins 10% for example), I'll add the remaining amount (minus any winnings and paper/ink costs) back to the jackpot pool for the next lotto.

| Correct Numbers Guessed | Payout Percentage |
| --- | --- |
| 5 + Powerball | 75% |
| 4 + Powerball | TBD |
| 3 + Powerball | TBD |
| 2 + Powerball | TBD |
| 1 + Powerball | TBD |
| 5 | TBD |
| 4 | TBD |
| 3 | TBD |
| Powerball Only | TBD |

**Comment by SigningOrgan** [comment]
Looks good. How would we purchase tickets?

**Comment by MyNameIsKodos** [comment]
Once I start it, tickets will _probably_ end up being 10 Silva a piece, without a purchase limit.  Most likely done in person, as I'll have to print each ticket personally.  I really hope to speak with Flenix about a creative supply of paper for the sake of needing it for the printer, but failing that I'll just do a tree farm.  But most of the costs will end up being ink sacs and paper to print more tickets.
